import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavigationBar from "@/components/navbar/navigation-bar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <title>정보시스템학과 학생회 정원</title>
      </head>
      <body>
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
